# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - Feature
    exclude:
    - master/*
    - tonywork/*
    - charlie/*


pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Proj2'
    organization: 'project2rev'
    scannerMode: 'MSBuild'
    projectKey: 'project2rev'
    extraProperties: 'sonar.exclusions=**/lib/**'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: ./

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: |
     HelpByPros.Test/HelpByPros.Test.csproj
     HelpByPros.BusinessLogic/HelpAByPros.BusinessLogic.csproj
     HelpByPros.sln    # Pass a solution instead of a csproj.
    arguments: --configuration $(buildConfiguration) --collect "XPlat Code Coverage"

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result